### ISSUE TITLE
Homestar can't find Hue on Windows

### ISSUE THREAD

**Issue by promanik** [dpjanes/homestar-hue#5]
I configured my Windows 7 machine as per the instructions. When I try and configure homestar, it cannot find the device. I can see the device as a Network device (192.168.1.24) in Windows explorer, and it runs fine using my iphone. 

Querying this port using http://192.168.1.24/description.xml returns:

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.24:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (192.168.1.24)</friendlyName>
<manufacturer>Royal Philips Electronics</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>MYS/N</serialNumber>
<UDN>MYUUID</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<height>120</height>
<width>120</width>
<depth>24</depth>
<url>hue_logo_3.png</url>
</icon>
</iconList>
</device>
</root>
```

Any suggestions of things to try? Running configure finds other devices on the networks, but not the Hue.

**Comment by dpjanes** [comment]
I think I just pushed a fix for this. The issue was they've changed the
Model Number and I wasn't detecting it in the configuration code. Update
this package and let me know.

**Comment by promanik** [comment]
It still takes time to find the Hue units on Windows (compared to a Mac running on the same network). However, it can detect the Hue with this change.

**Comment by dpjanes** [comment]
I think the Windows delay might be related to UPnP discovery. I'll give it a try when I boot up a Windows box.
