### ISSUE TITLE
username is not a valid api parameter anymore for hue bridge, can't pair any bridge with recent firmware

### ISSUE THREAD

**Issue by gnovos** [dpjanes/homestar-hue#6]
In HueLightBridge.js line 490 there is a `username' parameter being provided like so:

```
.send({
        devicetype: "test user",
        username: account_value
    })
```

This causes my bridge to respond saying that is an invalid parameter like so:

```
{ error: 
 { type: 6,
   address: '/username',
   description: 'parameter, username, not available' } }
```

and then the bridge won't pair properly.  According to the way they do a registration ing the [getting started guide](http://www.developers.meethue.com/documentation/getting-started) I think the appropriate way is maybe something like this:

```
.send({
        devicetype: "homestar#" + account_value
    })
```

However, then you'll need to read the response and cache the username it gives you.

**Comment by dpjanes** [comment]
I've just committed a version that should be forward and backward compatible, including your changes. I have not pushed it to NPM. Can you give it a test

**Comment by gnovos** [comment]
This works for me, thanks!
